#####################################################################################################################
#
# This is required to integrate dv_test.exs with mix test
#
# Below code was generated by mix new, which is part of Elixir
#
# Elixir is licensed under the Apache License version 2.0
#
# See Elixir licensing details in LICENSE and NOTICE
#
#####################################################################################################################
ExUnit.start(seed: 0)
